In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


In [2]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU is available!
Using GPU: Tesla T4


# creating tensors


In [3]:
a = torch.empty(2,3)

In [4]:
type(a)

torch.Tensor

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2,3)

tensor([[0.5332, 0.7976, 0.7992],
        [0.9740, 0.2613, 0.1411]])

In [9]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(200)
torch.rand(2,4)

tensor([[0.5939, 0.5008, 0.9961, 0.0311],
        [0.1716, 0.9481, 0.6470, 0.9265]])

In [12]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [14]:
# Tensor shapes

X = torch.tensor([[1,2,3],[4,5,6]])

In [15]:
X

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
X.shape

torch.Size([2, 3])

In [17]:
torch.empty_like(X)

tensor([[          293288435, 4635705220378015972, 4661726013461248228],
        [4681742012764214613,                  80,                  96]])

In [18]:
torch.zeros_like(X)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.ones_like(X)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
torch.rand_like(X,dtype=torch.float32)

tensor([[0.6200, 0.3349, 0.7323],
        [0.7349, 0.5005, 0.5612]])

In [21]:
# Tensor data types

X.dtype

torch.int64

In [22]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [24]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [25]:
X.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [26]:
# Mathematical Operations

X = torch.rand(2,2)

X

tensor([[0.8819, 0.1196],
        [0.7567, 0.9652]])

In [27]:
X + 2

X - 2

X * 3

X / 4

(X * 100)//3

((X * 100)//3)%2

X**2



tensor([[0.7777, 0.0143],
        [0.5726, 0.9316]])

In [28]:
# element wise operations

a = torch.rand(5,5)
b = torch.rand(5,5)

print(a)
print(b)

tensor([[0.3415, 0.6738, 0.0434, 0.8690, 0.4230],
        [0.4261, 0.3563, 0.9433, 0.7455, 0.8324],
        [0.6025, 0.5628, 0.0328, 0.9285, 0.1075],
        [0.7076, 0.1293, 0.7931, 0.5836, 0.4422],
        [0.5337, 0.8569, 0.4688, 0.5481, 0.6912]])
tensor([[0.0546, 0.6161, 0.6045, 0.0642, 0.4319],
        [0.2216, 0.3402, 0.1202, 0.7940, 0.3730],
        [0.2692, 0.9407, 0.7457, 0.8160, 0.5397],
        [0.9911, 0.2796, 0.3074, 0.1001, 0.2273],
        [0.5663, 0.9883, 0.9610, 0.3131, 0.9271]])


In [29]:
a + b

a - b

a * b

a / b

a ** b

a % b

tensor([[0.0138, 0.0577, 0.0434, 0.0347, 0.4230],
        [0.2044, 0.0161, 0.1020, 0.7455, 0.0865],
        [0.0640, 0.5628, 0.0328, 0.1125, 0.1075],
        [0.7076, 0.1293, 0.1783, 0.0832, 0.2149],
        [0.5337, 0.8569, 0.4688, 0.2349, 0.6912]])

In [30]:
c = torch.tensor([1,-2,3,-4])

In [31]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [32]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [33]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [35]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [36]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [37]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [38]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [40]:
# reduction operations

e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[2., 2., 7.],
        [4., 0., 4.]])

In [41]:
torch.mean(e)

tensor(3.1667)

In [42]:
torch.mean(e, dim=0)

tensor([3.0000, 1.0000, 5.5000])

In [43]:
torch.median(e)

tensor(2.)

In [44]:
torch.max(e)
torch.min(e)

tensor(0.)

In [45]:
torch.prod(e)

tensor(0.)

In [46]:
torch.std(e)

tensor(2.4014)

In [47]:
torch.var(e)

tensor(5.7667)

In [48]:
torch.argmin(e)

tensor(4)

In [49]:
# matrix operations

f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[8, 9, 4],
        [3, 6, 4]])
tensor([[5, 8],
        [4, 8],
        [1, 1]])


In [50]:
torch.matmul(f,g)

tensor([[ 80, 140],
        [ 43,  76]])

In [51]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

torch.dot(vector1, vector2)

tensor(11)

In [52]:
torch.transpose(f,0,1)

tensor([[8, 3],
        [9, 6],
        [4, 4]])

In [53]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)

h

tensor([[1., 8., 0.],
        [1., 9., 6.],
        [1., 1., 7.]])

In [54]:
torch.det(h)

tensor(49.)

In [55]:
torch.inverse(h)

tensor([[ 1.1633, -1.1429,  0.9796],
        [-0.0204,  0.1429, -0.1224],
        [-0.1633,  0.1429,  0.0204]])

In [56]:
# comparisons operations

i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 6, 6],
        [5, 7, 3]])
tensor([[5, 8, 8],
        [5, 2, 6]])


In [58]:
i > j

i < j

i == j

i != j

tensor([[ True,  True,  True],
        [False,  True,  True]])

In [59]:
# special functions
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)


In [60]:
k

tensor([[9., 5., 4.],
        [4., 1., 4.]])

In [61]:
torch.log(k)

tensor([[2.1972, 1.6094, 1.3863],
        [1.3863, 0.0000, 1.3863]])

In [62]:
torch.exp(k)

tensor([[8.1031e+03, 1.4841e+02, 5.4598e+01],
        [5.4598e+01, 2.7183e+00, 5.4598e+01]])

In [63]:
torch.sqrt(k)

tensor([[3.0000, 2.2361, 2.0000],
        [2.0000, 1.0000, 2.0000]])

In [64]:
torch.sigmoid(k)

tensor([[0.9999, 0.9933, 0.9820],
        [0.9820, 0.7311, 0.9820]])

In [65]:
torch.softmax(k, dim=0)

tensor([[0.9933, 0.9820, 0.5000],
        [0.0067, 0.0180, 0.5000]])

In [66]:
torch.relu(k)

tensor([[9., 5., 4.],
        [4., 1., 4.]])

In [67]:
# Inplace operations

m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.4734, 0.0871, 0.7159],
        [0.5075, 0.8763, 0.0907]])
tensor([[0.9908, 0.3387, 0.1062],
        [0.5113, 0.8146, 0.5761]])


In [68]:
m.add_(n)

tensor([[1.4642, 0.4258, 0.8222],
        [1.0188, 1.6909, 0.6668]])

In [69]:
m

tensor([[1.4642, 0.4258, 0.8222],
        [1.0188, 1.6909, 0.6668]])

In [70]:
n

tensor([[0.9908, 0.3387, 0.1062],
        [0.5113, 0.8146, 0.5761]])

In [71]:
torch.relu(m)

tensor([[1.4642, 0.4258, 0.8222],
        [1.0188, 1.6909, 0.6668]])

In [72]:
m.relu_()

tensor([[1.4642, 0.4258, 0.8222],
        [1.0188, 1.6909, 0.6668]])

In [73]:
m

tensor([[1.4642, 0.4258, 0.8222],
        [1.0188, 1.6909, 0.6668]])

In [74]:
# copying tensor

a = torch.rand(2,3)
a

tensor([[0.2741, 0.7979, 0.2672],
        [0.2250, 0.4968, 0.9454]])

In [75]:
b = a

In [76]:
b

tensor([[0.2741, 0.7979, 0.2672],
        [0.2250, 0.4968, 0.9454]])

In [77]:
a[0][0] = 100

In [78]:
a

tensor([[100.0000,   0.7979,   0.2672],
        [  0.2250,   0.4968,   0.9454]])

In [79]:
b

tensor([[100.0000,   0.7979,   0.2672],
        [  0.2250,   0.4968,   0.9454]])

In [80]:
id(b)

132422878714272

In [81]:
id(a)

132422878714272

In [82]:
b = a.clone()

In [83]:
a

tensor([[100.0000,   0.7979,   0.2672],
        [  0.2250,   0.4968,   0.9454]])

In [84]:
b

tensor([[100.0000,   0.7979,   0.2672],
        [  0.2250,   0.4968,   0.9454]])

In [85]:
a[0][0] = 300

In [86]:
b

tensor([[100.0000,   0.7979,   0.2672],
        [  0.2250,   0.4968,   0.9454]])

In [87]:
id(a)

132422878714272

In [88]:
id(b)

132422878714912